### Wallet API Tests
@baseUrl = http://localhost:4000/api/wallet


### 1. Create Wallet
POST {{baseUrl}}/create
Content-Type: application/json
  
{
  "userId": "81acb703-4f9c-49b2-ad67-50505bbe7338",
  "walletAddress": "0x1234567890abcdef1234567890abcdef12345678",
  "currency": "USDT",
  "balance": 1000.00
}

### 2. Get Wallet by User ID
GET {{baseUrl}}/81acb703-4f9c-49b2-ad67-50505bbe7338

### 3. Update Wallet
PUT {{baseUrl}}/a0cdf2dc-1af2-436b-bd0f-c3461599b3f6
Content-Type: application/json

{
  "walletAddress": "0x9876543210fedcba9876543210fedcba98765432",
  "balance": 1500.00
}

### 4. Delete Wallet
DELETE {{baseUrl}}/81acb703-4f9c-49b2-ad67-50505bbe7338
